CREATE TABLE IF NOT EXISTS audit_event (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor TEXT NOT NULL,
  action TEXT NOT NULL,
  context JSONB NOT NULL
);
CREATE TABLE IF NOT EXISTS receipt (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL DEFAULT now(),
  kind TEXT NOT NULL,
  details JSONB NOT NULL,
  sha256 CHAR(64) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_receipt_kind_ts ON receipt(kind, ts DESC);
