repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: [check, --fix]

  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args: [-ll]
        files: ^(apps/backend|packages)/.*\.py$

  - repo: local
    hooks:
      - id: safety
        name: safety
        entry: safety
        language: python
        pass_filenames: false
        additional_dependencies:
          - safety==2.3.5
        args: [check, --full-report]
