name: Bug report
description: Report a problem and help us reproduce it
title: "bug: <short summary>"
labels: ["status:todo", "priority:medium"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: "Include steps to reproduce, expected vs actual."
      placeholder: "1) ... 2) ... 3) ..."
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: "OS, Python/Node versions, repro branch/commit, etc."
  - type: input
    id: area_label
    attributes:
      label: Area label to add (area:*)
      placeholder: "area:backend"
      description: "Pick at least one area:* label before submitting."
  - type: checkboxes
    id: families
    attributes:
      label: Label families
      options:
        - label: "I will ensure exactly one of: type:*, status:*, priority:*; and ≥1 area:*"
          required: true
