name: Feature request
description: Propose an enhancement or new capability
title: "feat: <short summary>"
labels: ["status:todo", "priority:medium", "type:feature"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: "What problem does this solve? What is the desired outcome?"
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope & acceptance
      description: "Non-goals, constraints, acceptance checks."
  - type: input
    id: area_label
    attributes:
      label: Area label to add (area:*)
      placeholder: "area:ml"
      description: "Pick at least one area:* label before submitting."
  - type: checkboxes
    id: families
    attributes:
      label: Label families
      options:
        - label: "I will ensure exactly one of: type:*, status:*, priority:*; and ≥1 area:*"
          required: true
