name: "Epic: Phase 1 – Document Processing Foundation"
description: Track Phase 1 deliverables (ingestion, anchoring, provenance)
title: "Epic: Phase 1 – Document Processing"
labels: ["type:feature","status:in-progress","priority:high","area:backend"]
body:
  - type: markdown
    attributes:
      value: |
        Scope: MinIO upload API, routing (Lambda/EC2), SHA-256 anchors, PROV-O init, tests.
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      options:
        - label: "Routing implemented + unit tests"
        - label: "Anchoring implemented + unit tests"
        - label: "Provenance ingestion logging (Neo4j Cypher generation) + unit tests"
        - label: "Perf smoke + workflow green"
        - label: "Docs stubs updated"
