CREATE CONSTRAINT IF NOT EXISTS
FOR (c:Constitution) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS
FOR (r:Rule) REQUIRE r.id IS UNIQUE;
CREATE CONSTRAINT IF NOT EXISTS
FOR (d:Decision) REQUIRE d.id IS UNIQUE;
CALL db.labels() YIELD label RETURN label;
