[tool.poetry]
name = "darf-config"
version = "0.1.0"  
description = "DARF configuration utilities"
authors = ["darf"]

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
