name: CI Fail-Open Guard
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure ENGINE_FAIL_OPEN is not set in CI
        run: |
          if [ -n "${ENGINE_FAIL_OPEN:-}" ]; then
            echo "ENGINE_FAIL_OPEN must be unset in CI" >&2
            exit 1
          fi
