name: E2 Readiness Tracker
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/e2_target_tracker.py'
      - '.github/workflows/e2-readiness.yml'
      - 'scripts/pure_bridge_run.sh'
      - 'scripts/metrics_validate.py'
jobs:
  e2-readiness:
    # Run only when PR has the label 'ci:track-e2'
    if: contains(join(fromJson(toJson(github.event.pull_request.labels)).*.name, ','), 'ci:track-e2')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Produce PURE receipt (wrapper + bridge fallback)
        run: bash scripts/pure_bridge_run.sh
      - name: Validate metrics receipts
        run: |
          pip install jsonschema
          python scripts/metrics_validate.py --strict
      - name: Compute E2 readiness
        run: |
          python scripts/e2_target_tracker.py --target 0.50 --out e2_readiness.json
          cat e2_readiness.json
      - name: Upload E2 readiness artifact
        uses: actions/upload-artifact@v4
        with:
          name: e2-readiness
          path: e2_readiness.json
          if-no-files-found: error
