name: end_of_log_on_pr_merge
on:
  pull_request:
    types: [closed]
jobs:
  eol:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate report body
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq >/dev/null
          echo "END_OF_LOG" > eol.txt
          echo "" >> eol.txt
          echo "- PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}" >> eol.txt
          echo "- Branch: ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }}" >> eol.txt
          echo "- Repo: ${{ github.repository }}" >> eol.txt
          echo "" >> eol.txt
          echo "Summary:" >> eol.txt
          echo "- What shipped: documentation + reporting pipeline" >> eol.txt
          echo "- Blockers: none" >> eol.txt
          echo "- Pointers: docs/theory/*, .github/workflows/end_of_log.yml" >> eol.txt
          printf "::set-output name=body::%s" "$(sed ':a;N;$!ba;s/\n/%0A/g' eol.txt)" || true
      - name: Post as PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ISSUE: ${{ github.event.pull_request.number }}
        run: |
          body="$(cat eol.txt)"
          curl -sS -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE/comments" \
            -d "$(jq -nc --arg body "$body" '{body:$body}')"
