name: Hygiene
on:
  push:
  pull_request:

jobs:
  block-heavy:
    name: Block tracked caches and large files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if banned tracked paths exist
        shell: bash
        run: |
          set -euo pipefail
          banned="$(git ls-files 'models/cache/**' 'var/**' 2>/dev/null || true)"
          if [ -n "$banned" ]; then
            echo "Found tracked banned paths:"
            echo "$banned"
            exit 1
          fi
      - name: Fail if any non-LFS file >25MB
        shell: bash
        run: |
          set -euo pipefail
          big_files=""
          while IFS= read -r -d '' f; do
            # skip directories and symlinks
            [ -f "$f" ] || continue
            size_kb="$(du -k "$f" | awk '{print $1}')"
            if [ "${size_kb:-0}" -gt 25600 ]; then
              big_files="${big_files}\n${f}"
            fi
          done < <(git ls-files -z)
          if [ -n "$big_files" ]; then
            echo -e "Found >25MB non-LFS files:${big_files}"
            exit 1
          fi

  tests:
    name: Smoke tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install test deps
        shell: bash
        run: |
          set -euo pipefail
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Ensure pytest present even if requirements.txt missing minimal deps
          python - <<'PY'
try:
  import pytest  # noqa: F401
except Exception:
  import sys, subprocess
  subprocess.check_call([sys.executable, "-m", "pip", "install", "pytest"])
PY
      - name: Run unit + smoke tests
        env:
          DARF_BYPASS_MAP: ""
        shell: bash
        run: |
          set -euo pipefail
          pytest -q
