name: Metrics Receipt Validate
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/schemas/metrics_v1.json'
      - 'scripts/metrics_validate.py'
      - 'scripts/relex_ci_smoke.py'
      - '.github/workflows/metrics-validate.yml'
  push:
    branches: [ feat/phase7g-config, feat/phase7g-relation-baseline, feat/phase7g-pure-baseline ]
    paths:
      - 'docs/schemas/metrics_v1.json'
      - 'scripts/metrics_validate.py'
      - 'scripts/relex_ci_smoke.py'
      - '.github/workflows/metrics-validate.yml'
jobs:
  validate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Produce metrics via RE smoke
        run: python scripts/relex_ci_smoke.py
      - name: Install validator deps
        run: pip install jsonschema
      - name: Validate metrics receipts (strict)
        run: python scripts/metrics_validate.py --strict
