name: Packaging/Lifecycle Smoke
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'scripts/packaging_smoke.sh'
      - 'scripts/relex_ci_smoke.py'
      - 'packages/darf_config/**'
      - 'configs/.env.sample'
      - '.github/workflows/packaging-smoke.yml'
  push:
    branches: [ feat/phase7g-config ]
    paths:
      - 'scripts/packaging_smoke.sh'
      - 'scripts/relex_ci_smoke.py'
      - 'packages/darf_config/**'
      - 'configs/.env.sample'
      - '.github/workflows/packaging-smoke.yml'
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Prepare env
        run: |
          mkdir -p configs
          cp configs/.env.sample configs/.env.local
      - name: Run RE smoke (no containers in CI)
        run: python scripts/relex_ci_smoke.py
