name: Performance (opt-in)
on:
  workflow_dispatch:
    inputs:
      run_perf:
        description: 'Run perf jobs? (1=yes)'
        required: false
        default: '0'
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
env:
  RUN_PERF: ${{ github.event.inputs.run_perf || '0' }}
jobs:
  perf:
    if: env.RUN_PERF == '1'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show gate
        run: echo "RUN_PERF=${RUN_PERF} → perf job running by opt-in"
      # TODO: add real benchmarks here (guarded by the same gate)
