name: Phase-3 Pipeline (scaffold)
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  pipeline-scaffold:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest; fi || true
          pip install pytest
      - name: Run pipeline scaffold tests
        run: pytest -q tests/pipeline -vv -s
