name: policy-guide-ownership
on:
  pull_request:
    types: [opened, synchronize, edited, reopened, ready_for_review, labeled, unlabeled]
jobs:
  guide_ownership:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Guard Operating Guide ownership
        shell: bash
        run: |
          set -euo pipefail
          event="$GITHUB_EVENT_PATH"
          labels="$(jq -r '.pull_request.labels[].name' "$event" || true)"
          base_ref="${{ github.base_ref }}"
          # Work out base ref when job is triggered on forks/edits
          if [ -z "$base_ref" ] || [ "$base_ref" = "null" ]; then
            base_ref="$(jq -r '.pull_request.base.ref' "$event")"
          fi
          git fetch origin "$base_ref:$base_ref" || true
          changed="$(git diff --name-only "origin/$base_ref"...HEAD || true)"

          # If the Operating Guide changed, require the owner approval label
          if echo "$changed" | grep -xq 'agent/AGENT_OPERATING_GUIDE.md'; then
            echo "Detected change to agent/AGENT_OPERATING_GUIDE.md"
            if ! echo "$labels" | grep -xq 'owner:guide-ok'; then
              echo "::error ::Changes to AGENT_OPERATING_GUIDE.md require label 'owner:guide-ok' from the guide owner."
              exit 1
            else
              echo "Owner label present (owner:guide-ok) — allowing change."
            fi
          else
            echo "Operating Guide not changed — nothing to enforce."
          fi
