name: RE Pipeline Smoke
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/relex/**'
      - 'scripts/relex_ci_smoke.py'
      - 'data/scierc_norm/**'
      - '.github/workflows/relex-smoke.yml'
  push:
    branches: [ feat/phase7g-config ]
    paths:
      - 'apps/relex/**'
      - 'scripts/relex_ci_smoke.py'
      - 'data/scierc_norm/**'
      - '.github/workflows/relex-smoke.yml'
jobs:
  relex-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Run RE smoke (heuristic stdlib)
        run: python scripts/relex_ci_smoke.py
