name: OpenDARF v0.1.0 Receipt Validation

on:
  push:
    paths:
      - 'scripts/**'
      - 'var/receipts/**'
      - '.github/workflows/validation.yml'
      - 'scripts/evidence/**'
      - 'scripts/internal/**'
  pull_request:
    paths:
      - 'scripts/**'
      - 'var/receipts/**'
      - '.github/workflows/validation.yml'
      - 'scripts/evidence/**'
      - 'scripts/internal/**'

jobs:
  validate-v010:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure jq present
        run: jq --version || sudo apt-get update && sudo apt-get install -y jq

      - name: Run non-fatal validator (order-aware)
        run: |
          bash scripts/evidence/validate_receipt_v010.sh || true

      - name: Enforce PASS (fail CI if non-canonical)
        run: |
          bash scripts/evidence/validate_receipt_v010.sh | tee /tmp/vres.txt || true
          grep -q "\[PASS\] Canonical v0.1.0 receipt." /tmp/vres.txt
